[book]
title = "Markdown Book"
authors = ["Samantha"]
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/nlp-rs/rust-template"

[output.katex]
[preprocessor.katex]
trust = true
